#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🟡 pre push the application start build 🟡🟡"
echo "Build HR App 🟧"
npm run buil
echo "HR app build succesfuly 🟢"
echo "🟢🟢🟢 All build done well 🟢🟢🟢"